/// <reference types="vite/client" />

// Generated by build/keyboard-index.ts from the files in keyboards/.
declare module 'virtual:keyboard-index' {
  const index: { path: string; name: string; vendorId: number; productId: number }[];
  export default index;
}
