/// <reference types="vite/client" />

// Generated by build/keyboard-index.ts from the files in keyboards/.
declare module 'virtual:keyboard-index' {
  const index: import('./core/keyboard-list').KeyboardEntry[];
  export default index;
}
